version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - auth-api
      - todos-api
      - users-api

  auth-api:
    build: ./auth-api
    ports:
      - "8081:8080"

  todos-api:
    build: ./todos-api
    ports:
      - "8082:8080"

  users-api:
    build: ./users-api
    ports:
      - "8083:8080"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"